# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  libgrt_config = release
  gob_config = release
endif
ifeq ($(config),debug)
  libgrt_config = debug
  gob_config = debug
endif

PROJECTS := libgrt gob

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

libgrt:
ifneq (,$(libgrt_config))
	@echo "==== Building libgrt ($(libgrt_config)) ===="
	@${MAKE} --no-print-directory -C . -f libgrt.make config=$(libgrt_config)
endif

gob: libgrt
ifneq (,$(gob_config))
	@echo "==== Building gob ($(gob_config)) ===="
	@${MAKE} --no-print-directory -C . -f gob.make config=$(gob_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f libgrt.make clean
	@${MAKE} --no-print-directory -C . -f gob.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo "  debug"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   libgrt"
	@echo "   gob"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"